
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  # post:
  #     categories: /categories
  #     archives: /archives
  #     tags: /tags
  archives: /archives
  tags: /tags
  categories: /categories
#  Papers: /paper
#  project: /project
#  activity: /activity
  search: /search
  # about: http://www.fooying.com
  # rss: /atom.xml

# Miscelaneous
favicon: favicon.ico
logo:

share:
    show: false
    img:
    img_alt:
    tip_text: test

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# baidu url js push
baidu_url_js_push: true


# comment extend, support gialk
comment_extend:
    gitalk:
        enable: false
        owner: Github username
        repo: issue repo name
        admin: github username
        clientID: xxx
        clientSecret: xxx

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true

# auto generate excerpt length.
excerpt_start:
  0
excerpt_end:
  100

#footer
index_page: http://www.fooying.com
main_site: http://www.fooying.com
github: https://github.com/fooying
links_url: /links
